name: class_selector_fail
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  browser:  "any"
  pathos:  "any"
  polymer:  "any"
  logging:  "any"
# custom <class_selector_fail dependencies>
# end <class_selector_fail dependencies>

