name: class_selector_fail
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  browser:  ">=0.5.20 <0.5.21"
  pathos:  ">=0.5.20 <0.5.21"
  polymer:  "any"
  logging:  ">=0.5.20 <0.5.21"
  logging_handlers:  ">=0.5.0+3 <0.5.1"
# custom <class_selector_fail dependencies>
# end <class_selector_fail dependencies>

