name: tic_tac_toe
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
description: >
  Simple tic tac toe game
dependencies:
  browser:  ">=0.5.20 <0.5.21"
  pathos:  ">=0.5.20 <0.5.21"
  polymer:  "any"
  logging:  ">=0.5.20 <0.5.21"
  logging_handlers:  ">=0.5.0+3 <0.5.1"
  split_panel:
      git: 
        url: git://github.com/patefacio/split_panel
        ref: HEAD

# custom <tic_tac_toe dependencies>
  unittest: any
  logging: any
  logging_handlers: any

  ebisu_web_ui:
    git: git://github.com/patefacio/ebisu_web_ui
  
# end <tic_tac_toe dependencies>

