name: tic_tac_toe
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
# custom <tic_tac_toe dependencies>
  unittest: any
  logging: any
  logging_handlers: any
# end <tic_tac_toe dependencies>

