name: tic_tac_toe
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
description: >
  Simple tic tac toe game
dependencies:
  browser: "any"

  pathos: "any"

  polymer: "any"

  logging: "any"

  split_panel:
      git: 
        url: git://github.com/patefacio/split_panel
        ref: HEAD

  logging_handlers: ">=0.5.0+3 <0.5.1"

# custom <tic_tac_toe dependencies>

# end <tic_tac_toe dependencies>

dev_dependencies:
# custom <tic_tac_toe dev dependencies>

  unittest: any

# end <tic_tac_toe dev dependencies>


